services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
  redis:
      image: redis:latest
      container_name: redis_container
      ports:
        - "6380:6379"
      volumes:
        - ./redisdata:/data
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080