"""init

Revision ID: b2527dd2ccb1
Revises: 
Create Date: 2025-09-07 16:52:59.081436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2527dd2ccb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))

    # op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # цикл по всем записям с заполнением поля
    # op.add_column('users', sa.Column('email', sa.String(), nullable=False))


    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
